var Resource=require("./resource.js");function RoboidWriteQueue(a){this.setSize(a);this.output=Array(19)}RoboidWriteQueue.prototype.setSize=function(a){this.buffer=Array(a);this.mask=a-1;this.consumer=this.provider=0};RoboidWriteQueue.prototype.reset=function(){this.consumer=this.provider=0};
RoboidWriteQueue.prototype.stringToUtf8ByteArray=function(a){for(var b=[],c=0,d,e=0;e<a.length;e++)d=a.charCodeAt(e),128>d?b[c++]=d:(2048>d?b[c++]=d>>6|192:(55296==(d&64512)&&e+1<a.length&&56320==(a.charCodeAt(e+1)&64512)?(d=65536+((d&1023)<<10)+(a.charCodeAt(++e)&1023),b[c++]=d>>18|240,b[c++]=d>>12&63|128):b[c++]=d>>12|224,b[c++]=d>>6&63|128),b[c++]=d&63|128);return b};
RoboidWriteQueue.prototype.push=function(a,b){var c=this.buffer,d=this.mask,e=this.provider,f=this.consumer;if(0<a.length)for(var g=this.stringToUtf8ByteArray(a),h=0;h<g.length;++h)(e-f&d)==d&&(f=f+1&d),c[e]=g[h],e=e+1&d;b&&((e-f&d)==d&&(f=f+1&d),c[e]=13,e=e+1&d);this.provider=e;this.consumer=f};RoboidWriteQueue.prototype.pushRaw=function(a,b,c){for(var d=this.buffer,e=this.mask,f=this.provider,g=this.consumer;b<c;++b)(f-g&e)==e&&(g=g+1&e),d[f]=a[b],f=f+1&e;this.provider=f;this.consumer=g};
RoboidWriteQueue.prototype.pop=function(){var a=this.provider,b=this.consumer;if(a!=b){var c=this.buffer,d=this.mask,e=this.output,f=a-b&d;18<f&&(f=18);e[0]=f;for(var g=1;g<=f&&b!=a;++g)e[g]=c[b],b=b+1&d;for(;18>=g;++g)e[g]=0;this.consumer=b;return e}};function RoboidReadQueue(a){this.setSize(a)}RoboidReadQueue.prototype.setSize=function(a){this.buffer=Array(a);this.mask=a-1;this.consumer=this.provider=0};RoboidReadQueue.prototype.reset=function(){this.consumer=this.provider=0};
RoboidReadQueue.prototype.utf8ByteArrayToString=function(a,b,c){for(var d=this.mask,e=[],f=0,g,h,k,l;b!=c;)if(g=a[b],b=b+1&d,128>g)e[f++]=String.fromCharCode(g);else if(191<g&&224>g){if(b==c)break;h=a[b];b=b+1&d;e[f++]=String.fromCharCode((g&31)<<6|h&63)}else if(239<g&&365>g){if(b==c)break;h=a[b];b=b+1&d;if(b==c)break;k=a[b];b=b+1&d;if(b==c)break;l=a[b];b=b+1&d;g=((g&7)<<18|(h&63)<<12|(k&63)<<6|l&63)-65536;e[f++]=String.fromCharCode(55296+(g>>10));e[f++]=String.fromCharCode(56320+(g&1023))}else{if(b==
c)break;h=a[b];b=b+1&d;if(b==c)break;k=a[b];b=b+1&d;e[f++]=String.fromCharCode((g&15)<<12|(h&63)<<6|k&63)}this.consumer=b;return e.join("")};RoboidReadQueue.prototype.push=function(a,b){var c=a[b];if(0<c){18<c&&(c=18);var d=this.buffer,e=this.mask,f=this.provider,g=this.consumer;c+=b;for(var h=1+b;h<=c;++h)(f-g&e)==e&&(g=g+1&e),d[f]=a[h],f=f+1&e;this.provider=f;this.consumer=g}};
RoboidReadQueue.prototype.pop=function(a){var b=this.provider,c=this.consumer;if(b!=c){if(0==a)return this.utf8ByteArrayToString(this.buffer,c,b);for(var d=this.buffer,e=this.mask,f=-1;c!=b;){if(d[c]==a){f=c;break}c=c+1&e}if(0<=f)return a=this.utf8ByteArrayToString(d,this.consumer,f),this.consumer=this.consumer+1&e,a}};
function Hamster(a){this.sensory={map:0,signalStrength:0,leftProximity:0,rightProximity:0,leftFloor:0,rightFloor:0,accelerationX:0,accelerationY:0,accelerationZ:0,light:0,temperature:0,inputA:0,inputB:0,lineTracerState:0,tilt:0,batteryState:2,handFound:!1};this.motoring={module:"hamster",index:a,map:4227858432,leftWheel:0,rightWheel:0,buzzer:0,outputA:0,outputB:0,leftLed:0,rightLed:0,note:0,lineTracerMode:0,lineTracerSpeed:5,ioModeA:0,ioModeB:0,motion:0,radius:5};this.wheelId=this.blockId=0;this.lineTracerCallback=
this.wheelTimer=void 0;this.boardCount=this.boardState=this.boardCommand=0;this.boardCallback=void 0;this.noteId=0;this.noteTimer2=this.noteTimer1=void 0;this.ioId=0;this.ioTimer=void 0;this.tempo=60;this.timeouts=[]}
Hamster.prototype.reset=function(){var a=this.motoring;a.map=4261150720;a.leftWheel=0;a.rightWheel=0;a.buzzer=0;a.outputA=0;a.outputB=0;a.leftLed=0;a.rightLed=0;a.note=0;a.lineTracerMode=0;a.lineTracerSpeed=5;a.ioModeA=0;a.ioModeB=0;a.motion=0;a.radius=5;this.wheelId=this.blockId=0;this.lineTracerCallback=this.wheelTimer=void 0;this.boardCount=this.boardState=this.boardCommand=0;this.boardCallback=void 0;this.noteId=0;this.noteTimer2=this.noteTimer1=void 0;this.ioId=0;this.ioTimer=void 0;this.tempo=
60;this.__removeAllTimeouts()};Hamster.prototype.__removeTimeout=function(a){clearTimeout(a);a=this.timeouts.indexOf(a);0<=a&&this.timeouts.splice(a,1)};Hamster.prototype.__removeAllTimeouts=function(){var a=this.timeouts,b;for(b in a)clearTimeout(a[b]);this.timeouts=[]};Hamster.prototype.clearMotoring=function(){this.motoring.map=4227858432};Hamster.prototype.clearEvent=function(){};Hamster.prototype.__issueWheelId=function(){return this.wheelId=this.blockId=this.blockId%65535+1};
Hamster.prototype.__cancelWheel=function(){this.wheelId=0;void 0!==this.wheelTimer&&this.__removeTimeout(this.wheelTimer);this.wheelTimer=void 0};Hamster.prototype.__setLineTracerMode=function(a){this.motoring.lineTracerMode=a;this.motoring.map|=2097152};Hamster.prototype.__setLineTracerSpeed=function(a){this.motoring.lineTracerSpeed=a;this.motoring.map|=1048576};Hamster.prototype.__cancelLineTracer=function(){this.lineTracerCallback=void 0};
Hamster.prototype.__cancelBoard=function(){this.boardCount=this.boardState=this.boardCommand=0;this.boardCallback=void 0};Hamster.prototype.__setLeftLed=function(a){this.motoring.leftLed=a;this.motoring.map|=16777216};Hamster.prototype.__setRightLed=function(a){this.motoring.rightLed=a;this.motoring.map|=8388608};Hamster.prototype.__setNote=function(a){this.motoring.note=a;this.motoring.map|=4194304};Hamster.prototype.__issueNoteId=function(){return this.noteId=this.blockId=this.blockId%65535+1};
Hamster.prototype.__cancelNote=function(){this.noteId=0;void 0!==this.noteTimer1&&this.__removeTimeout(this.noteTimer1);void 0!==this.noteTimer2&&this.__removeTimeout(this.noteTimer2);this.noteTimer2=this.noteTimer1=void 0};Hamster.prototype.__setIoModeA=function(a){this.motoring.ioModeA=a;this.motoring.map|=524288};Hamster.prototype.__setIoModeB=function(a){this.motoring.ioModeB=a;this.motoring.map|=262144};
Hamster.prototype.__issueIoId=function(){return this.ioId=this.blockId=this.blockId%65535+1};Hamster.prototype.__cancelIo=function(){this.ioId=0;void 0!==this.ioTimer&&this.__removeTimeout(this.ioTimer);this.ioTimer=void 0};
Hamster.prototype.handleSensory=function(){var a=this,b=a.sensory;if(a.lineTracerCallback&&0!=(b.map&16)&&64==b.lineTracerState){a.__setLineTracerMode(0);var c=a.lineTracerCallback;a.__cancelLineTracer();c&&c()}if(a.boardCallback){var d=a.motoring;if(1==a.boardCommand)switch(a.boardState){case 1:2>a.boardCount?(50>b.leftFloor&&50>b.rightFloor?a.boardCount++:a.boardCount=0,b=b.leftFloor-b.rightFloor,d.leftWheel=45+.25*b,d.rightWheel=45-.25*b):(a.boardCount=0,a.boardState=2);break;case 2:b=b.leftFloor-
b.rightFloor;d.leftWheel=45+.25*b;d.rightWheel=45-.25*b;a.boardState=3;a.wheelTimer=setTimeout(function(){d.leftWheel=0;d.rightWheel=0;a.boardState=4;void 0!==a.wheelTimer&&a.__removeTimeout(a.wheelTimer);a.wheelTimer=void 0},250);a.timeouts.push(a.wheelTimer);break;case 3:b=b.leftFloor-b.rightFloor;d.leftWheel=45+.25*b;d.rightWheel=45-.25*b;break;case 4:d.leftWheel=0,d.rightWheel=0,b=a.boardCallback,a.__cancelBoard(),b&&b()}else if(2==a.boardCommand)switch(a.boardState){case 1:2>a.boardCount?50<
b.leftFloor&&a.boardCount++:(a.boardCount=0,a.boardState=2);break;case 2:20>b.leftFloor&&(a.boardState=3);break;case 3:2>a.boardCount?20>b.leftFloor&&a.boardCount++:(a.boardCount=0,a.boardState=4);break;case 4:50<b.leftFloor&&(a.boardState=5);break;case 5:b=b.leftFloor-b.rightFloor,-15<b?(d.leftWheel=0,d.rightWheel=0,b=a.boardCallback,a.__cancelBoard(),b&&b()):(d.leftWheel=.5*b,d.rightWheel=.5*-b)}else if(3==a.boardCommand)switch(a.boardState){case 1:2>a.boardCount?50<b.rightFloor&&a.boardCount++:
(a.boardCount=0,a.boardState=2);break;case 2:20>b.rightFloor&&(a.boardState=3);break;case 3:2>a.boardCount?20>b.rightFloor&&a.boardCount++:(a.boardCount=0,a.boardState=4);break;case 4:50<b.rightFloor&&(a.boardState=5);break;case 5:b=b.rightFloor-b.leftFloor,-15<b?(d.leftWheel=0,d.rightWheel=0,b=a.boardCallback,a.__cancelBoard(),b&&b()):(d.leftWheel=.5*-b,d.rightWheel=.5*b)}}};
Hamster.prototype.__board=function(a,b,c,d){var e=this.motoring;this.__cancelWheel();this.__cancelLineTracer();e.leftWheel=a;e.rightWheel=b;e.motion=0;this.boardCommand=c;this.boardCount=0;this.boardState=1;this.boardCallback=d;this.__setLineTracerMode(0)};Hamster.prototype.boardForward=function(a){this.__board(45,45,1,a)};Hamster.prototype.boardTurn=function(a,b){"left"==a?this.__board(-45,45,2,b):this.__board(45,-45,3,b)};
Hamster.prototype.__motion=function(a,b,c,d,e){var f=this,g=f.motoring;f.__cancelBoard();f.__cancelWheel();f.__cancelLineTracer();if((d=parseFloat(d))&&0<d){var h=f.__issueWheelId();g.leftWheel=b;g.rightWheel=c;g.motion=a;f.__setLineTracerMode(0);f.wheelTimer=setTimeout(function(){f.wheelId==h&&(g.leftWheel=0,g.rightWheel=0,g.motion=0,f.__cancelWheel(),e())},1E3*d);f.timeouts.push(f.wheelTimer)}else g.leftWheel=0,g.rightWheel=0,g.motion=0,f.__setLineTracerMode(0),e()};
Hamster.prototype.moveForward=function(a){this.__motion(1,30,30,1,a)};Hamster.prototype.moveBackward=function(a){this.__motion(2,-30,-30,1,a)};Hamster.prototype.turn=function(a,b){"left"==a?this.__motion(3,-30,30,1,b):this.__motion(4,30,-30,1,b)};Hamster.prototype.moveForwardSecs=function(a,b){0>a?this.__motion(2,-30,-30,-a,b):this.__motion(1,30,30,a,b)};Hamster.prototype.moveBackwardSecs=function(a,b){0>a?this.__motion(1,30,30,-a,b):this.__motion(2,-30,-30,a,b)};
Hamster.prototype.turnSecs=function(a,b,c){"left"==a?0>b?this.__motion(4,30,-30,-b,c):this.__motion(3,-30,30,b,c):0>b?this.__motion(3,-30,30,-b,c):this.__motion(4,30,-30,b,c)};Hamster.prototype.__stopMotion=function(){var a=this.motoring;this.__cancelBoard();this.__cancelWheel();this.__cancelLineTracer();a.leftWheel=0;a.rightWheel=0;a.motion=0;this.__setLineTracerMode(0)};Hamster.prototype.moveForwardUnit=function(a,b,c){"seconds"==b?this.moveForwardSecs(a,c):this.__stopMotion()};
Hamster.prototype.moveBackwardUnit=function(a,b,c){"seconds"==b?this.moveBackwardSecs(a,c):this.__stopMotion()};Hamster.prototype.turnUnit=function(a,b,c,d){"seconds"==c?this.turnSecs(a,b,d):this.__stopMotion()};
Hamster.prototype.pivotWheelUnit=function(a,b,c,d,e){"seconds"==c?"left"==a?"forward"==d?0>b?this.__motion(6,0,-30,-b,e):this.__motion(5,0,30,b,e):0>b?this.__motion(5,0,30,-b,e):this.__motion(6,0,-30,b,e):"forward"==d?0>b?this.__motion(8,-30,0,-b,e):this.__motion(7,30,0,b,e):0>b?this.__motion(7,30,0,-b,e):this.__motion(8,-30,0,b,e):this.__stopMotion()};
Hamster.prototype.swingBodyUnit=function(a,b,c,d,e,f){"seconds"==c?(d=parseFloat(d),"number"==typeof d&&0<=d?(this.motoring.radius=d,"left"==a?"forward"==e?0>b?this.__motion(10,0,0,-b,f):this.__motion(9,0,0,b,f):0>b?this.__motion(9,0,0,-b,f):this.__motion(10,0,0,b,f):"forward"==e?0>b?this.__motion(12,0,0,-b,f):this.__motion(11,0,0,b,f):0>b?this.__motion(11,0,0,-b,f):this.__motion(12,0,0,b,f)):(this.__stopMotion(),f())):this.__stopMotion()};
Hamster.prototype.pivotUnit=function(a,b,c,d,e){"seconds"==c?"left pen"==a?"forward"==d?0>b?this.__motion(14,0,0,-b,e):this.__motion(13,0,0,b,e):0>b?this.__motion(13,0,0,-b,e):this.__motion(14,0,0,b,e):"right pen"==a?"forward"==d?0>b?this.__motion(16,0,0,-b,e):this.__motion(15,0,0,b,e):0>b?this.__motion(15,0,0,-b,e):this.__motion(16,0,0,b,e):"left wheel"==a?"forward"==d?0>b?this.__motion(6,0,-30,-b,e):this.__motion(5,0,30,b,e):0>b?this.__motion(5,0,30,-b,e):this.__motion(6,0,-30,b,e):"forward"==d?
0>b?this.__motion(8,-30,0,-b,e):this.__motion(7,30,0,b,e):0>b?this.__motion(7,30,0,-b,e):this.__motion(8,-30,0,b,e):this.__stopMotion()};
Hamster.prototype.swingUnit=function(a,b,c,d,e,f,g){"seconds"==d?(e=parseFloat(e),"number"==typeof e&&0<=e?(this.motoring.radius=e,"left pen"==a?"left"==b?"forward"==f?0>c?this.__motion(18,0,0,-c,g):this.__motion(17,0,0,c,g):0>c?this.__motion(17,0,0,-c,g):this.__motion(18,0,0,c,g):"forward"==f?0>c?this.__motion(20,0,0,-c,g):this.__motion(19,0,0,c,g):0>c?this.__motion(19,0,0,-c,g):this.__motion(20,0,0,c,g):"right pen"==a?"left"==b?"forward"==f?0>c?this.__motion(22,0,0,-c,g):this.__motion(21,0,0,c,
g):0>c?this.__motion(21,0,0,-c,g):this.__motion(22,0,0,c,g):"forward"==f?0>c?this.__motion(24,0,0,-c,g):this.__motion(23,0,0,c,g):0>c?this.__motion(23,0,0,-c,g):this.__motion(24,0,0,c,g):"left"==b?"forward"==f?0>c?this.__motion(10,0,0,-c,g):this.__motion(9,0,0,c,g):0>c?this.__motion(9,0,0,-c,g):this.__motion(10,0,0,c,g):"forward"==f?0>c?this.__motion(12,0,0,-c,g):this.__motion(11,0,0,c,g):0>c?this.__motion(11,0,0,-c,g):this.__motion(12,0,0,c,g)):(this.__stopMotion(),g())):this.__stopMotion()};
Hamster.prototype.setWheels=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelWheel();this.__cancelLineTracer();a=parseFloat(a);b=parseFloat(b);"number"==typeof a&&(c.leftWheel=a);"number"==typeof b&&(c.rightWheel=b);c.motion=0;this.__setLineTracerMode(0)};
Hamster.prototype.changeWheels=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelWheel();this.__cancelLineTracer();a=parseFloat(a);b=parseFloat(b);"number"==typeof a&&(c.leftWheel+=a);"number"==typeof b&&(c.rightWheel+=b);c.motion=0;this.__setLineTracerMode(0)};
Hamster.prototype.setWheel=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelWheel();this.__cancelLineTracer();b=parseFloat(b);"number"==typeof b&&("left"==a?c.leftWheel=b:("right"!=a&&(c.leftWheel=b),c.rightWheel=b));c.motion=0;this.__setLineTracerMode(0)};
Hamster.prototype.changeWheel=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelWheel();this.__cancelLineTracer();b=parseFloat(b);"number"==typeof b&&("left"==a?c.leftWheel+=b:("right"!=a&&(c.leftWheel+=b),c.rightWheel+=b));c.motion=0;this.__setLineTracerMode(0)};
Hamster.prototype.followLine=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelWheel();this.__cancelLineTracer();var d=1;"right"==b?d=2:"both"==b&&(d=3);"white"==a&&(d+=7);c.leftWheel=0;c.rightWheel=0;c.motion=0;this.__setLineTracerMode(d)};
Hamster.prototype.followLineUntil=function(a,b,c){var d=this.motoring;this.__cancelBoard();this.__cancelWheel();var e=4;"right"==b?e=5:"front"==b?e=6:"rear"==b&&(e=7);"white"==a&&(e+=7);d.leftWheel=0;d.rightWheel=0;d.motion=0;this.__setLineTracerMode(e);this.lineTracerCallback=c};Hamster.prototype.setLineTracerSpeed=function(a){a=parseInt(a);"number"==typeof a&&this.__setLineTracerSpeed(a)};Hamster.prototype.setLineTracerGain=function(a){};
Hamster.prototype.stop=function(){var a=this.motoring;this.__cancelBoard();this.__cancelWheel();this.__cancelLineTracer();a.leftWheel=0;a.rightWheel=0;a.motion=0;this.__setLineTracerMode(0)};Hamster.prototype.__COLORS={red:4,orange:4,yellow:6,green:2,"sky blue":3,blue:1,violet:5,purple:5,white:7};Hamster.prototype.setLed=function(a,b){(b=this.__COLORS[b])&&0<b&&("left"==a?this.__setLeftLed(b):("right"!=a&&this.__setLeftLed(b),this.__setRightLed(b)))};
Hamster.prototype.clearLed=function(a){"left"==a?this.__setLeftLed(0):("right"!=a&&this.__setLeftLed(0),this.__setRightLed(0))};Hamster.prototype.setRgbArray=function(a,b){};Hamster.prototype.setRgb=function(a,b,c,d){};Hamster.prototype.changeRgb=function(a,b,c,d){};
Hamster.prototype.runBeep=function(a,b,c){if(a){var d=this,e=d.motoring;e.buzzer=440;d.__setNote(0);d.noteTimer1=setTimeout(function(){b&&d.noteId!=b||(e.buzzer=0,void 0!==d.noteTimer1&&d.__removeTimeout(d.noteTimer1),d.noteTimer1=void 0)},100);d.timeouts.push(d.noteTimer1);d.noteTimer2=setTimeout(function(){b&&d.noteId!=b||(e.buzzer=0,void 0!==d.noteTimer2&&d.__removeTimeout(d.noteTimer2),d.noteTimer2=void 0,0>a?d.runBeep(-1,b,c):1==a?(d.__cancelNote(),b&&c&&c()):d.runBeep(a-1,b,c))},200);d.timeouts.push(d.noteTimer2)}};
Hamster.prototype.beep=function(a){this.__cancelNote();var b=this.__issueNoteId();this.runBeep(1,b,a)};Hamster.prototype.playSound=function(a,b){this.__cancelNote();this.motoring.buzzer=0;this.__setNote(0);b=parseInt(b);"beep"==a&&b&&this.runBeep(b)};Hamster.prototype.playSoundUntil=function(a,b,c){this.__cancelNote();this.motoring.buzzer=0;this.__setNote(0);(b=parseInt(b))?"beep"==a&&(a=this.__issueNoteId(),this.runBeep(b,a,c)):c()};
Hamster.prototype.setBuzzer=function(a){var b=this.motoring;this.__cancelNote();a=parseFloat(a);"number"==typeof a&&(b.buzzer=a);this.__setNote(0)};Hamster.prototype.changeBuzzer=function(a){var b=this.motoring;this.__cancelNote();a=parseFloat(a);"number"==typeof a&&(b.buzzer+=a);this.__setNote(0)};Hamster.prototype.clearBuzzer=function(){this.__cancelNote();this.motoring.buzzer=0;this.__setNote(0)};Hamster.prototype.clearSound=function(){this.clearBuzzer()};
Hamster.prototype.__NOTES={C:4,"C\u266f (D\u266d)":5,D:6,"D\u266f (E\u266d)":7,E:8,F:9,"F\u266f (G\u266d)":10,G:11,"G\u266f (A\u266d)":12,A:13,"A\u266f (B\u266d)":14,B:15};Hamster.prototype.playNote=function(a,b){var c=this.motoring;this.__cancelNote();a=this.__NOTES[a];b=parseInt(b);c.buzzer=0;a&&b&&0<b&&8>b?this.__setNote(a+12*(b-1)):this.__setNote(0)};
Hamster.prototype.playNoteBeat=function(a,b,c,d){var e=this,f=e.motoring;e.__cancelNote();a=e.__NOTES[a];b=parseInt(b);c=parseFloat(c);f.buzzer=0;if(a&&b&&0<b&&8>b&&c&&0<c&&0<e.tempo){var g=e.__issueNoteId();e.__setNote(a+12*(b-1));a=6E4*c/e.tempo;b=100<a?100:0;0<b&&(e.noteTimer1=setTimeout(function(){e.noteId==g&&(e.__setNote(0),void 0!==e.noteTimer1&&e.__removeTimeout(e.noteTimer1),e.noteTimer1=void 0)},a-b),e.timeouts.push(e.noteTimer1));e.noteTimer2=setTimeout(function(){e.noteId==g&&(e.__setNote(0),
e.__cancelNote(),d())},a);e.timeouts.push(e.noteTimer2)}else e.__setNote(0),d()};Hamster.prototype.restBeat=function(a,b){var c=this,d=c.motoring;c.__cancelNote();a=parseFloat(a);d.buzzer=0;c.__setNote(0);if(a&&0<a&&0<c.tempo){var e=c.__issueNoteId();c.noteTimer1=setTimeout(function(){c.noteId==e&&(c.__cancelNote(),b())},6E4*a/c.tempo);c.timeouts.push(c.noteTimer1)}else b()};Hamster.prototype.setTempo=function(a){a=parseFloat(a);"number"==typeof a&&(this.tempo=a,1>this.tempo&&(this.tempo=1))};
Hamster.prototype.changeTempo=function(a){a=parseFloat(a);"number"==typeof a&&(this.tempo+=a,1>this.tempo&&(this.tempo=1))};Hamster.prototype.getLeftProximity=function(){return this.sensory.leftProximity};Hamster.prototype.getRightProximity=function(){return this.sensory.rightProximity};Hamster.prototype.getLeftFloor=function(){return this.sensory.leftFloor};Hamster.prototype.getRightFloor=function(){return this.sensory.rightFloor};Hamster.prototype.getAccelerationX=function(){return this.sensory.accelerationX};
Hamster.prototype.getAccelerationY=function(){return this.sensory.accelerationY};Hamster.prototype.getAccelerationZ=function(){return this.sensory.accelerationZ};Hamster.prototype.getLight=function(){return this.sensory.light};Hamster.prototype.getTemperature=function(){return this.sensory.temperature};Hamster.prototype.getSignalStrength=function(){return this.sensory.signalStrength};
Hamster.prototype.checkHandFound=function(){var a=this.sensory;return void 0===a.handFound?40<a.leftProximity||40<a.rightProximity:a.handFound};Hamster.prototype.checkTilt=function(a){switch(a){case "tilt forward":return 1==this.sensory.tilt;case "tilt backward":return-1==this.sensory.tilt;case "tilt left":return 2==this.sensory.tilt;case "tilt right":return-2==this.sensory.tilt;case "tilt flip":return 3==this.sensory.tilt;case "not tilt":return-3==this.sensory.tilt}return!1};
Hamster.prototype.__BATTERY_STATES={normal:2,low:1,empty:0};Hamster.prototype.checkBattery=function(a){return this.sensory.batteryState==this.__BATTERY_STATES[a]};Hamster.prototype.__IO_MODES={"analog input":0,"digital input":1,"servo output":8,"pwm output":9,"digital output":10};Hamster.prototype.setIoMode=function(a,b){this.__cancelIo();b=this.__IO_MODES[b];"number"==typeof b&&("A"==a?this.__setIoModeA(b):("B"!=a&&this.__setIoModeA(b),this.__setIoModeB(b)))};
Hamster.prototype.setOutput=function(a,b){var c=this.motoring;this.__cancelIo();b=parseFloat(b);"number"==typeof b&&("A"==a?c.outputA=b:("B"!=a&&(c.outputA=b),c.outputB=b))};Hamster.prototype.changeOutput=function(a,b){var c=this.motoring;this.__cancelIo();b=parseFloat(b);"number"==typeof b&&("A"==a?c.outputA+=b:("B"!=a&&(c.outputA+=b),c.outputB+=b))};
Hamster.prototype.gripper=function(a,b){var c=this,d=c.motoring;c.__cancelIo();var e=c.__issueIoId();c.__setIoModeA(10);c.__setIoModeB(10);"open"==a?(d.outputA=1,d.outputB=0):(d.outputA=0,d.outputB=1);c.ioTimer=setTimeout(function(){c.ioId==e&&(c.__cancelIo(),b())},500);c.timeouts.push(c.ioTimer)};Hamster.prototype.releaseGripper=function(){var a=this.motoring;this.__cancelIo();this.__setIoModeA(10);this.__setIoModeB(10);a.outputA=0;a.outputB=0};Hamster.prototype.getInputA=function(){return this.sensory.inputA};
Hamster.prototype.getInputB=function(){return this.sensory.inputB};Hamster.prototype.writeSerial=function(a,b,c){this.__cancelIo()};Hamster.prototype.readSerialUltil=function(a,b){this.__cancelIo()};Hamster.prototype.setSerialRate=function(a){this.__cancelIo()};Hamster.prototype.getSerialInput=function(){return""};
function HamsterS(a){this.sensory={map1:0,map2:0,signalStrength:0,leftProximity:0,rightProximity:0,leftFloor:0,rightFloor:0,accelerationX:0,accelerationY:0,accelerationZ:0,light:0,temperature:0,inputA:0,inputB:0,tilt:0,serial:"",pulseCount:0,wheelState:0,soundState:0,lineTracerState:0,batteryState:2,handFound:!1};this.motoring={module:"hamsterS",index:a,map1:4227858432,map2:3221225472,leftWheel:0,rightWheel:0,leftRed:0,leftGreen:0,leftBlue:0,rightRed:0,rightGreen:0,rightBlue:0,buzzer:0,outputA:0,
outputB:0,pulse:0,note:0,sound:0,lineTracerMode:0,lineTracerGain:4,lineTracerSpeed:5,ioModeA:0,ioModeB:0,serial:void 0,motionType:0,motionUnit:0,motionSpeed:0,motionValue:0,motionRadius:0};this.blockId=0;this.lineTracerCallback=this.motionCallback=void 0;this.boardCount=this.boardState=this.boardCommand=0;this.boardCallback=void 0;this.currentSound=0;this.soundRepeat=1;this.soundCallback=void 0;this.noteId=0;this.noteTimer2=this.noteTimer1=void 0;this.ioId=0;this.ioTimer=void 0;this.serialDelimiter=
0;this.serialRate=176;this.writeSerialCallbacks=[];this.readSerialCallbacks=[];this.serialInput="";this.tap=this.freeFall=!1;this.tempo=60;this.speed=5;this.gain=-1;this.writeQueue=new RoboidWriteQueue(64);this.readQueue=new RoboidReadQueue(64);this.timeouts=[]}
HamsterS.prototype.reset=function(){var a=this.motoring;a.map1=4235984896;a.map2=4194304E3;a.leftWheel=0;a.rightWheel=0;a.leftRed=0;a.leftGreen=0;a.leftBlue=0;a.rightRed=0;a.rightGreen=0;a.rightBlue=0;a.buzzer=0;a.outputA=0;a.outputB=0;a.pulse=0;a.note=0;a.sound=0;a.lineTracerMode=0;a.lineTracerGain=4;a.lineTracerSpeed=5;a.ioModeA=0;a.ioModeB=0;a.serial=void 0;a.motionType=0;a.motionUnit=0;a.motionSpeed=0;a.motionValue=0;this.blockId=a.motionRadius=0;this.lineTracerCallback=this.motionCallback=void 0;
this.boardCount=this.boardState=this.boardCommand=0;this.boardCallback=void 0;this.currentSound=0;this.soundRepeat=1;this.soundCallback=void 0;this.noteId=0;this.noteTimer2=this.noteTimer1=void 0;this.ioId=0;this.ioTimer=void 0;this.serialDelimiter=0;this.serialRate=176;this.writeSerialCallbacks=[];this.readSerialCallbacks=[];this.serialInput="";this.tap=this.freeFall=!1;this.tempo=60;this.speed=5;this.gain=-1;this.__removeAllTimeouts();this.writeQueue.reset();this.readQueue.reset()};
HamsterS.prototype.__removeTimeout=function(a){clearTimeout(a);a=this.timeouts.indexOf(a);0<=a&&this.timeouts.splice(a,1)};HamsterS.prototype.__removeAllTimeouts=function(){var a=this.timeouts,b;for(b in a)clearTimeout(a[b]);this.timeouts=[]};HamsterS.prototype.__fireWriteSerialCallbacks=function(){var a=this.writeSerialCallbacks,b;for(b in a)a[b]();this.writeSerialCallbacks=[]};
HamsterS.prototype.__fireReadSerialCallbacks=function(){var a=this.readSerialCallbacks,b;for(b in a)a[b]();this.readSerialCallbacks=[]};HamsterS.prototype.clearMotoring=function(){this.motoring.map1=4227858432;this.motoring.map2=3221225472};HamsterS.prototype.clearEvent=function(){this.tap=this.freeFall=!1};HamsterS.prototype.__setPulse=function(a){this.motoring.pulse=a;this.motoring.map2|=536870912};
HamsterS.prototype.__setLineTracerMode=function(a){this.motoring.lineTracerMode=a;this.motoring.map1|=2097152};HamsterS.prototype.__setLineTracerGain=function(a){this.motoring.lineTracerGain=a;this.motoring.map2|=134217728};HamsterS.prototype.__setLineTracerSpeed=function(a){this.motoring.lineTracerSpeed=a;this.motoring.map1|=1048576};HamsterS.prototype.__cancelLineTracer=function(){this.lineTracerCallback=void 0};
HamsterS.prototype.__setMotion=function(a,b,c,d,e){var f=this.motoring;f.motionType=a;f.motionUnit=b;f.motionSpeed=c;f.motionValue=d;f.motionRadius=e;f.map2|=33554432};HamsterS.prototype.__cancelMotion=function(){this.motionCallback=void 0};HamsterS.prototype.__cancelBoard=function(){this.boardCount=this.boardState=this.boardCommand=0;this.boardCallback=void 0};HamsterS.prototype.__setNote=function(a){this.motoring.note=a;this.motoring.map1|=4194304};
HamsterS.prototype.__issueNoteId=function(){return this.noteId=this.blockId=this.blockId%65535+1};HamsterS.prototype.__cancelNote=function(){this.noteId=0;void 0!==this.noteTimer1&&this.__removeTimeout(this.noteTimer1);void 0!==this.noteTimer2&&this.__removeTimeout(this.noteTimer2);this.noteTimer2=this.noteTimer1=void 0};HamsterS.prototype.__setSound=function(a){this.motoring.sound=a;this.motoring.map2|=268435456};
HamsterS.prototype.__runSound=function(a,b){"number"!=typeof b&&(b=1);0>b&&(b=-1);b&&(this.currentSound=a,this.soundRepeat=b,this.__setSound(a))};HamsterS.prototype.__cancelSound=function(){this.soundCallback=void 0};HamsterS.prototype.__setIoModeA=function(a){this.motoring.ioModeA=a;this.motoring.map1|=524288};HamsterS.prototype.__setIoModeB=function(a){this.motoring.ioModeB=a;this.motoring.map1|=262144};HamsterS.prototype.__issueIoId=function(){return this.ioId=this.blockId=this.blockId%65535+1};
HamsterS.prototype.__cancelIo=function(){this.ioId=0;void 0!==this.ioTimer&&this.__removeTimeout(this.ioTimer);this.ioTimer=void 0};HamsterS.prototype.__setSerial=function(a){var b=this.motoring;void 0==b.serial&&(b.serial=Array(19));for(var c=0;19>c;++c)b.serial[c]=a[c];b.map2|=67108864};
HamsterS.prototype.handleSensory=function(){var a=this,b=a.sensory;b.map2&32768&&(a.freeFall=!0);b.map2&16384&&(a.tap=!0);if(a.lineTracerCallback&&0!=(b.map1&16)&&64==b.lineTracerState){a.__setLineTracerMode(0);var c=a.lineTracerCallback;a.__cancelLineTracer();c&&c()}if(a.boardCallback){var d=a.motoring;if(1==a.boardCommand)switch(a.boardState){case 1:2>a.boardCount?(50>b.leftFloor&&50>b.rightFloor?a.boardCount++:a.boardCount=0,c=b.leftFloor-b.rightFloor,d.leftWheel=45+.25*c,d.rightWheel=45-.25*c):
(a.boardCount=0,a.boardState=2);break;case 2:c=b.leftFloor-b.rightFloor;d.leftWheel=45+.25*c;d.rightWheel=45-.25*c;a.boardState=3;a.wheelTimer=setTimeout(function(){d.leftWheel=0;d.rightWheel=0;a.boardState=4;void 0!==a.wheelTimer&&a.__removeTimeout(a.wheelTimer);a.wheelTimer=void 0},250);a.timeouts.push(a.wheelTimer);break;case 3:c=b.leftFloor-b.rightFloor;d.leftWheel=45+.25*c;d.rightWheel=45-.25*c;break;case 4:d.leftWheel=0,d.rightWheel=0,c=a.boardCallback,a.__cancelBoard(),c&&c()}else if(2==a.boardCommand)switch(a.boardState){case 1:2>
a.boardCount?50<b.leftFloor&&a.boardCount++:(a.boardCount=0,a.boardState=2);break;case 2:20>b.leftFloor&&(a.boardState=3);break;case 3:2>a.boardCount?20>b.leftFloor&&a.boardCount++:(a.boardCount=0,a.boardState=4);break;case 4:50<b.leftFloor&&(a.boardState=5);break;case 5:c=b.leftFloor-b.rightFloor,-15<c?(d.leftWheel=0,d.rightWheel=0,c=a.boardCallback,a.__cancelBoard(),c&&c()):(d.leftWheel=.5*c,d.rightWheel=.5*-c)}else if(3==a.boardCommand)switch(a.boardState){case 1:2>a.boardCount?50<b.rightFloor&&
a.boardCount++:(a.boardCount=0,a.boardState=2);break;case 2:20>b.rightFloor&&(a.boardState=3);break;case 3:2>a.boardCount?20>b.rightFloor&&a.boardCount++:(a.boardCount=0,a.boardState=4);break;case 4:50<b.rightFloor&&(a.boardState=5);break;case 5:c=b.rightFloor-b.leftFloor,-15<c?(d.leftWheel=0,d.rightWheel=0,c=a.boardCallback,a.__cancelBoard(),c&&c()):(d.leftWheel=.5*-c,d.rightWheel=.5*c)}}a.motionCallback&&0!=(b.map2&2048)&&2==b.wheelState&&(a.motoring.leftWheel=0,a.motoring.rightWheel=0,c=a.motionCallback,
a.__cancelMotion(),c&&c());0!=(b.map2&1024)&&0==b.soundState&&(0<a.currentSound?0>a.soundRepeat?a.__runSound(a.currentSound,-1):1<a.soundRepeat?(a.soundRepeat--,a.__runSound(a.currentSound,a.soundRepeat)):(a.currentSound=0,a.soundRepeat=1,c=a.soundCallback,a.__cancelSound(),c&&c()):(a.currentSound=0,a.soundRepeat=1,c=a.soundCallback,a.__cancelSound(),c&&c()));b.map2&8192&&b.serial&&a.readQueue.push(b.serial,0);b.map2&512&&((b=a.writeQueue.pop())?a.__setSerial(b):a.__fireWriteSerialCallbacks());0<
a.readSerialCallbacks.length&&(b=a.readQueue.pop(a.serialDelimiter))&&(a.serialInput=b,a.__fireReadSerialCallbacks())};HamsterS.prototype.__board=function(a,b,c,d){var e=this.motoring;this.__cancelMotion();this.__cancelLineTracer();e.leftWheel=a;e.rightWheel=b;this.boardCommand=c;this.boardCount=0;this.boardState=1;this.boardCallback=d;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};HamsterS.prototype.boardForward=function(a){this.__board(45,45,1,a)};
HamsterS.prototype.boardTurn=function(a,b){"left"==a?this.__board(-45,45,2,b):this.__board(45,-45,3,b)};HamsterS.prototype.__UNITS={cm:1,degrees:1,seconds:2,pulses:3};HamsterS.prototype.__motion=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelLineTracer();c.leftWheel=0;c.rightWheel=0;this.__setPulse(0);this.__setMotion(a,1,0,0,0);this.motionCallback=b;this.__setLineTracerMode(0)};
HamsterS.prototype.__motionUnit=function(a,b,c,d){var e=this.motoring;this.__cancelBoard();this.__cancelMotion();this.__cancelLineTracer();e.leftWheel=0;e.rightWheel=0;this.__setPulse(0);(c=parseFloat(c))&&0<c?(this.__setMotion(a,b,0,c,0),this.motionCallback=d,this.__setLineTracerMode(0)):(this.__setMotion(0,0,0,0,0),this.__setLineTracerMode(0),d())};
HamsterS.prototype.__motionUnitRadius=function(a,b,c,d,e){var f=this.motoring;this.__cancelBoard();this.__cancelMotion();this.__cancelLineTracer();f.leftWheel=0;f.rightWheel=0;this.__setPulse(0);c=parseFloat(c);d=parseFloat(d);c&&0<c&&"number"==typeof d&&0<=d?(this.__setMotion(a,b,0,c,d),this.motionCallback=e,this.__setLineTracerMode(0)):(this.__setMotion(0,0,0,0,0),this.__setLineTracerMode(0),e())};HamsterS.prototype.moveForward=function(a){this.__motion(101,a)};
HamsterS.prototype.moveBackward=function(a){this.__motion(102,a)};HamsterS.prototype.turn=function(a,b){"left"==a?this.__motion(103,b):this.__motion(104,b)};HamsterS.prototype.moveForwardSecs=function(a,b){0>a?this.__motionUnit(2,2,-a,b):this.__motionUnit(1,2,a,b)};HamsterS.prototype.moveBackwardSecs=function(a,b){0>a?this.__motionUnit(1,2,-a,b):this.__motionUnit(2,2,a,b)};
HamsterS.prototype.turnSecs=function(a,b,c){"left"==a?0>b?this.__motionUnit(4,2,-b,c):this.__motionUnit(3,2,b,c):0>b?this.__motionUnit(3,2,-b,c):this.__motionUnit(4,2,b,c)};HamsterS.prototype.moveForwardUnit=function(a,b,c){0>a?this.__motionUnit(2,this.__UNITS[b],-a,c):this.__motionUnit(1,this.__UNITS[b],a,c)};HamsterS.prototype.moveBackwardUnit=function(a,b,c){0>a?this.__motionUnit(1,this.__UNITS[b],-a,c):this.__motionUnit(2,this.__UNITS[b],a,c)};
HamsterS.prototype.turnUnit=function(a,b,c,d){"left"==a?0>b?this.__motionUnit(4,this.__UNITS[c],-b,d):this.__motionUnit(3,this.__UNITS[c],b,d):0>b?this.__motionUnit(3,this.__UNITS[c],-b,d):this.__motionUnit(4,this.__UNITS[c],b,d)};
HamsterS.prototype.pivotWheelUnit=function(a,b,c,d,e){c=this.__UNITS[c];"left"==a?"forward"==d?0>b?this.__motionUnit(6,c,-b,e):this.__motionUnit(5,c,b,e):0>b?this.__motionUnit(5,c,-b,e):this.__motionUnit(6,c,b,e):"forward"==d?0>b?this.__motionUnit(8,c,-b,e):this.__motionUnit(7,c,b,e):0>b?this.__motionUnit(7,c,-b,e):this.__motionUnit(8,c,b,e)};
HamsterS.prototype.swingBodyUnit=function(a,b,c,d,e,f){c=this.__UNITS[c];"left"==a?"forward"==e?0>b?this.__motionUnitRadius(10,c,-b,d,f):this.__motionUnitRadius(9,c,b,d,f):0>b?this.__motionUnitRadius(9,c,-b,d,f):this.__motionUnitRadius(10,c,b,d,f):"forward"==e?0>b?this.__motionUnitRadius(12,c,-b,d,f):this.__motionUnitRadius(11,c,b,d,f):0>b?this.__motionUnitRadius(11,c,-b,d,f):this.__motionUnitRadius(12,c,b,d,f)};
HamsterS.prototype.pivotUnit=function(a,b,c,d,e){c=this.__UNITS[c];"left pen"==a?"forward"==d?0>b?this.__motionUnit(14,c,-b,e):this.__motionUnit(13,c,b,e):0>b?this.__motionUnit(13,c,-b,e):this.__motionUnit(14,c,b,e):"right pen"==a?"forward"==d?0>b?this.__motionUnit(16,c,-b,e):this.__motionUnit(15,c,b,e):0>b?this.__motionUnit(15,c,-b,e):this.__motionUnit(16,c,b,e):"left wheel"==a?"forward"==d?0>b?this.__motionUnit(6,c,-b,e):this.__motionUnit(5,c,b,e):0>b?this.__motionUnit(5,c,-b,e):this.__motionUnit(6,
c,b,e):"forward"==d?0>b?this.__motionUnit(8,c,-b,e):this.__motionUnit(7,c,b,e):0>b?this.__motionUnit(7,c,-b,e):this.__motionUnit(8,c,b,e)};
HamsterS.prototype.swingUnit=function(a,b,c,d,e,f,g){d=this.__UNITS[d];"left pen"==a?"left"==b?"forward"==f?0>c?this.__motionUnitRadius(18,d,-c,e,g):this.__motionUnitRadius(17,d,c,e,g):0>c?this.__motionUnitRadius(17,d,-c,e,g):this.__motionUnitRadius(18,d,c,e,g):"forward"==f?0>c?this.__motionUnitRadius(20,d,-c,e,g):this.__motionUnitRadius(19,d,c,e,g):0>c?this.__motionUnitRadius(19,d,-c,e,g):this.__motionUnitRadius(20,d,c,e,g):"right pen"==a?"left"==b?"forward"==f?0>c?this.__motionUnitRadius(22,d,-c,
e,g):this.__motionUnitRadius(21,d,c,e,g):0>c?this.__motionUnitRadius(21,d,-c,e,g):this.__motionUnitRadius(22,d,c,e,g):"forward"==f?0>c?this.__motionUnitRadius(24,d,-c,e,g):this.__motionUnitRadius(23,d,c,e,g):0>c?this.__motionUnitRadius(23,d,-c,e,g):this.__motionUnitRadius(24,d,c,e,g):"left"==b?"forward"==f?0>c?this.__motionUnitRadius(10,d,-c,e,g):this.__motionUnitRadius(9,d,c,e,g):0>c?this.__motionUnitRadius(9,d,-c,e,g):this.__motionUnitRadius(10,d,c,e,g):"forward"==f?0>c?this.__motionUnitRadius(12,
d,-c,e,g):this.__motionUnitRadius(11,d,c,e,g):0>c?this.__motionUnitRadius(11,d,-c,e,g):this.__motionUnitRadius(12,d,c,e,g)};HamsterS.prototype.setWheels=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelMotion();this.__cancelLineTracer();a=parseFloat(a);b=parseFloat(b);"number"==typeof a&&(c.leftWheel=a);"number"==typeof b&&(c.rightWheel=b);this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};
HamsterS.prototype.changeWheels=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelMotion();this.__cancelLineTracer();a=parseFloat(a);b=parseFloat(b);"number"==typeof a&&(c.leftWheel+=a);"number"==typeof b&&(c.rightWheel+=b);this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};
HamsterS.prototype.setWheel=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelMotion();this.__cancelLineTracer();b=parseFloat(b);"number"==typeof b&&("left"==a?c.leftWheel=b:("right"!=a&&(c.leftWheel=b),c.rightWheel=b));this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};
HamsterS.prototype.changeWheel=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelMotion();this.__cancelLineTracer();b=parseFloat(b);"number"==typeof b&&("left"==a?c.leftWheel+=b:("right"!=a&&(c.leftWheel+=b),c.rightWheel+=b));this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};
HamsterS.prototype.followLine=function(a,b){var c=this.motoring;this.__cancelBoard();this.__cancelMotion();this.__cancelLineTracer();var d=1;"right"==b?d=2:"both"==b&&(d=3);"white"==a&&(d+=7);c.leftWheel=0;c.rightWheel=0;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(d)};
HamsterS.prototype.followLineUntil=function(a,b,c){var d=this.motoring;this.__cancelBoard();this.__cancelMotion();var e=4;"right"==b?e=5:"front"==b?e=6:"rear"==b&&(e=7);"white"==a&&(e+=7);d.leftWheel=0;d.rightWheel=0;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(e);this.lineTracerCallback=c};HamsterS.prototype.__GAINS={1:6,2:6,3:5,4:5,5:4,6:4,7:3,8:3};
HamsterS.prototype.setLineTracerSpeed=function(a){a=parseInt(a);var b=this.gain;0>b&&(b=this.__GAINS[a]);a&&b&&0<a&&0<b&&(this.speed=a,this.__setLineTracerSpeed(a),this.__setLineTracerGain(b))};HamsterS.prototype.setLineTracerGain=function(a){(a=parseInt(a))&&0<a?(this.gain=a,this.__setLineTracerGain(a)):(this.gain=-1,(a=this.__GAINS[this.speed])&&0<a&&this.__setLineTracerGain(a))};
HamsterS.prototype.stop=function(){var a=this.motoring;this.__cancelBoard();this.__cancelMotion();this.__cancelLineTracer();a.leftWheel=0;a.rightWheel=0;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};HamsterS.prototype.__RGBS={red:[255,0,0],orange:[255,63,0],yellow:[255,255,0],green:[0,255,0],"sky blue":[0,255,255],blue:[0,0,255],violet:[63,0,255],purple:[255,0,255],white:[255,255,255]};
HamsterS.prototype.setLed=function(a,b){var c=this.__RGBS[b];c&&this.setRgb(a,c[0],c[1],c[2])};HamsterS.prototype.clearLed=function(a){this.setRgb(a,0,0,0)};HamsterS.prototype.setRgbArray=function(a,b){b&&this.setRgb(a,b[0],b[1],b[2])};
HamsterS.prototype.setRgb=function(a,b,c,d){var e=this.motoring;b=parseInt(b);c=parseInt(c);d=parseInt(d);"left"==a?("number"==typeof b&&(e.leftRed=b),"number"==typeof c&&(e.leftGreen=c),"number"==typeof d&&(e.leftBlue=d)):"right"==a?("number"==typeof b&&(e.rightRed=b),"number"==typeof c&&(e.rightGreen=c),"number"==typeof d&&(e.rightBlue=d)):("number"==typeof b&&(e.leftRed=b,e.rightRed=b),"number"==typeof c&&(e.leftGreen=c,e.rightGreen=c),"number"==typeof d&&(e.leftBlue=d,e.rightBlue=d))};
HamsterS.prototype.changeRgb=function(a,b,c,d){var e=this.motoring;b=parseInt(b);c=parseInt(c);d=parseInt(d);"left"==a?("number"==typeof b&&(e.leftRed+=b),"number"==typeof c&&(e.leftGreen+=c),"number"==typeof d&&(e.leftBlue+=d)):"right"==a?("number"==typeof b&&(e.rightRed+=b),"number"==typeof c&&(e.rightGreen+=c),"number"==typeof d&&(e.rightBlue+=d)):("number"==typeof b&&(e.leftRed+=b,e.rightRed+=b),"number"==typeof c&&(e.leftGreen+=c,e.rightGreen+=c),"number"==typeof d&&(e.leftBlue+=d,e.rightBlue+=
d))};HamsterS.prototype.__SOUNDS={beep:1,"random beep":2,noise:10,siren:3,engine:4,chop:11,robot:5,dibidibidip:8,"good job":9,happy:12,angry:13,sad:14,sleep:15,march:6,birthday:7};HamsterS.prototype.beep=function(a){this.playSoundUntil("beep",1,a)};HamsterS.prototype.playSound=function(a,b){var c=this.motoring;this.__cancelNote();this.__cancelSound();a=this.__SOUNDS[a];b=parseInt(b);c.buzzer=0;this.__setNote(0);a&&b?this.__runSound(a,b):this.__runSound(0)};
HamsterS.prototype.playSoundUntil=function(a,b,c){var d=this.motoring;this.__cancelNote();this.__cancelSound();a=this.__SOUNDS[a];b=parseInt(b);d.buzzer=0;this.__setNote(0);a&&b?(this.__runSound(a,b),this.soundCallback=c):(this.__runSound(0),c())};HamsterS.prototype.setBuzzer=function(a){var b=this.motoring;this.__cancelNote();this.__cancelSound();a=parseFloat(a);"number"==typeof a&&(b.buzzer=a);this.__setNote(0);this.__runSound(0)};
HamsterS.prototype.changeBuzzer=function(a){var b=this.motoring;this.__cancelNote();this.__cancelSound();a=parseFloat(a);"number"==typeof a&&(b.buzzer+=a);this.__setNote(0);this.__runSound(0)};HamsterS.prototype.clearBuzzer=function(){this.clearSound()};HamsterS.prototype.clearSound=function(){this.__cancelNote();this.__cancelSound();this.motoring.buzzer=0;this.__setNote(0);this.__runSound(0)};
HamsterS.prototype.__NOTES={C:4,"C\u266f (D\u266d)":5,D:6,"D\u266f (E\u266d)":7,E:8,F:9,"F\u266f (G\u266d)":10,G:11,"G\u266f (A\u266d)":12,A:13,"A\u266f (B\u266d)":14,B:15};HamsterS.prototype.playNote=function(a,b){var c=this.motoring;this.__cancelNote();this.__cancelSound();a=this.__NOTES[a];b=parseInt(b);c.buzzer=0;a&&b&&0<b&&8>b?this.__setNote(a+12*(b-1)):this.__setNote(0);this.__runSound(0)};
HamsterS.prototype.playNoteBeat=function(a,b,c,d){var e=this,f=e.motoring;e.__cancelNote();e.__cancelSound();a=this.__NOTES[a];b=parseInt(b);c=parseFloat(c);f.buzzer=0;if(a&&b&&0<b&&8>b&&c&&0<c&&0<e.tempo){var g=e.__issueNoteId();e.__setNote(a+12*(b-1));a=6E4*c/e.tempo;b=100<a?100:0;0<b&&(e.noteTimer1=setTimeout(function(){e.noteId==g&&(e.__setNote(0),void 0!==e.noteTimer1&&e.__removeTimeout(e.noteTimer1),e.noteTimer1=void 0)},a-b),e.timeouts.push(e.noteTimer1));e.noteTimer2=setTimeout(function(){e.noteId==
g&&(e.__setNote(0),e.__cancelNote(),d())},a);e.timeouts.push(e.noteTimer2);e.__runSound(0)}else e.__setNote(0),e.__runSound(0),d()};HamsterS.prototype.restBeat=function(a,b){var c=this,d=c.motoring;c.__cancelNote();c.__cancelSound();a=parseFloat(a);d.buzzer=0;c.__setNote(0);c.__runSound(0);if(a&&0<a&&0<c.tempo){var e=c.__issueNoteId();c.noteTimer1=setTimeout(function(){c.noteId==e&&(c.__cancelNote(),b())},6E4*a/c.tempo);c.timeouts.push(c.noteTimer1)}else b()};
HamsterS.prototype.setTempo=function(a){a=parseFloat(a);"number"==typeof a&&(this.tempo=a,1>this.tempo&&(this.tempo=1))};HamsterS.prototype.changeTempo=function(a){a=parseFloat(a);"number"==typeof a&&(this.tempo+=a,1>this.tempo&&(this.tempo=1))};HamsterS.prototype.getLeftProximity=function(){return this.sensory.leftProximity};HamsterS.prototype.getRightProximity=function(){return this.sensory.rightProximity};HamsterS.prototype.getLeftFloor=function(){return this.sensory.leftFloor};
HamsterS.prototype.getRightFloor=function(){return this.sensory.rightFloor};HamsterS.prototype.getAccelerationX=function(){return this.sensory.accelerationX};HamsterS.prototype.getAccelerationY=function(){return this.sensory.accelerationY};HamsterS.prototype.getAccelerationZ=function(){return this.sensory.accelerationZ};HamsterS.prototype.getLight=function(){return this.sensory.light};HamsterS.prototype.getTemperature=function(){return this.sensory.temperature};
HamsterS.prototype.getSignalStrength=function(){return this.sensory.signalStrength};HamsterS.prototype.checkHandFound=function(){var a=this.sensory;return void 0===a.handFound?50<a.leftProximity||50<a.rightProximity:a.handFound};
HamsterS.prototype.checkTilt=function(a){var b=this.sensory;switch(a){case "tilt forward":return 1==b.tilt;case "tilt backward":return-1==b.tilt;case "tilt left":return 2==b.tilt;case "tilt right":return-2==b.tilt;case "tilt flip":return 3==b.tilt;case "not tilt":return-3==b.tilt;case "tap":return this.tap;case "free fall":return this.freeFall}return!1};HamsterS.prototype.__BATTERY_STATES={normal:2,low:1,empty:0};HamsterS.prototype.checkBattery=function(a){return this.sensory.batteryState==this.__BATTERY_STATES[a]};
HamsterS.prototype.__IO_MODES={"analog input":0,"digital input":1,"digital input (pull up)":2,"digital input (pull down)":3,"voltage input":5,"servo output":8,"pwm output":9,"digital output":10};HamsterS.prototype.setIoMode=function(a,b){this.__cancelIo();b=this.__IO_MODES[b];"number"==typeof b&&("A"==a?this.__setIoModeA(b):("B"!=a&&this.__setIoModeA(b),this.__setIoModeB(b)))};
HamsterS.prototype.setOutput=function(a,b){var c=this.motoring;this.__cancelIo();b=parseFloat(b);"number"==typeof b&&("A"==a?c.outputA=b:("B"!=a&&(c.outputA=b),c.outputB=b))};HamsterS.prototype.changeOutput=function(a,b){var c=this.motoring;this.__cancelIo();b=parseFloat(b);"number"==typeof b&&("A"==a?c.outputA+=b:("B"!=a&&(c.outputA+=b),c.outputB+=b))};
HamsterS.prototype.gripper=function(a,b){var c=this,d=c.motoring;c.__cancelIo();var e=c.__issueIoId();c.__setIoModeA(10);c.__setIoModeB(10);"open"==a?(d.outputA=1,d.outputB=0):(d.outputA=0,d.outputB=1);c.ioTimer=setTimeout(function(){c.ioId==e&&(c.__cancelIo(),b())},500);c.timeouts.push(c.ioTimer)};HamsterS.prototype.releaseGripper=function(){var a=this.motoring;this.__cancelIo();this.__setIoModeA(10);this.__setIoModeB(10);a.outputA=0;a.outputB=0};HamsterS.prototype.getInputA=function(){return this.sensory.inputA};
HamsterS.prototype.getInputB=function(){return this.sensory.inputB};HamsterS.prototype.writeSerial=function(a,b,c){this.__cancelIo();this.__setIoModeA(this.serialRate);this.__setIoModeB(this.serialRate);var d=this.writeQueue;d.push(b,"string"!=a);if(a=d.pop())this.writeSerialCallbacks.push(c),this.__setSerial(a)};HamsterS.prototype.__SERIAL_DELIMITERS={all:0,"until new line":13,"until ,(comma)":44,"until :(colon)":58,"until $":36,"until #":35};
HamsterS.prototype.readSerialUltil=function(a,b){this.__cancelIo();this.__setIoModeA(this.serialRate);this.__setIoModeB(this.serialRate);a=this.__SERIAL_DELIMITERS[a];"number"==typeof a&&(this.serialDelimiter=a,this.readSerialCallbacks.push(b))};HamsterS.prototype.__SERIAL_BAUDS={9600:176,14400:177,19200:178,28800:179,38400:180,57600:181,76800:182,115200:183};HamsterS.prototype.setSerialRate=function(a){this.__cancelIo();(a=this.__SERIAL_BAUDS[a])&&0<a&&(this.serialRate=a,this.__setIoModeA(a),this.__setIoModeB(a))};
HamsterS.prototype.getSerialInput=function(){return this.serialInput};
var RoboidUtil={toNumber:function(a,b){void 0===b&&(b=0);var c=Number(a);return isNaN(c)?b:c},toBoolean:function(a){return"boolean"===typeof a?a:"string"===typeof a?""===a||"0"===a||"false"===a.toLowerCase()?!1:!0:!!a},toString:function(a){return String(a)},hexToRgb:function(a){a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(b,c,d,e){return c+c+d+d+e+e});return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null},decimalToRgb:function(a){var b=
a>>24&255;return{r:a>>16&255,g:a>>8&255,b:a&255,a:0<b?b:255}},toRgbArray:function(a){a="string"===typeof a&&"#"===a.substring(0,1)?RoboidUtil.hexToRgb(a):RoboidUtil.decimalToRgb(RoboidUtil.toNumber(a));return[a.r,a.g,a.b]}},RoboidRunner=function(a){this.creators=a;this.robots={};this.robotsByGroup={};this.robotsByModule={};this.packet={};this.retryId=void 0;this.canSend=this.alive=!1};
RoboidRunner.prototype.addRobotByModule=function(a,b,c){var d=this.robotsByModule[a];void 0===d&&(d=this.robotsByModule[a]={});d[b]=c};RoboidRunner.prototype.getOrCreateRobot=function(a,b,c){var d=this.robots,e=b+c,f=d[e];if(!f){var g=this.creators[b];g&&(f=g(c));f&&(d[e]=f,this.packet[e]=f.motoring,this.addRobotByModule(b,e,f))}return this.robotsByGroup[a+c]=f};RoboidRunner.prototype.getRobot=function(a,b){return this.robotsByGroup[a+b]};
RoboidRunner.prototype.clearMotorings=function(){var a=this.robots,b;for(b in a)a[b].clearMotoring()};RoboidRunner.prototype.afterTick=function(){var a=this.robots,b;for(b in a)a[b].clearEvent()};RoboidRunner.prototype.reset=function(a){if(a=this.robotsByModule[a])for(var b in a)a[b].reset()};
RoboidRunner.prototype.open=function(){try{var a=this,b=new WebSocket("ws://localhost:56417");b.binaryType="arraybuffer";a.socket=b;b.onmessage=function(c){try{var d=JSON.parse(c.data);if(0!=d.type)if(2==d.type)for(var e in d.modules);else if(0<=d.index){var f=a.getOrCreateRobot(d.group,d.module,d.index);f&&(f.clearEvent(),f.sensory=d,f.handleSensory())}}catch(g){}};b.onclose=function(){a.alive=!1;a.canSend=!1;void 0===a.retryId&&(a.retryId=setInterval(function(){a.alive?void 0!==a.retryId&&(clearInterval(a.retryId),
a.retryId=void 0):a.open()},2E3))};b.onopen=function(){a.alive=!0;var c=Date.now(),d=function(){if(a.canSend&&a.socket){if(Date.now()>c){try{var e=JSON.stringify(a.packet);a.canSend&&a.socket&&a.socket.send(e);a.clearMotorings()}catch(f){}c+=20}setTimeout(d,5)}};a.canSend=!0;d()};return!0}catch(c){}return!1};RoboidRunner.prototype.close=function(){this.canSend=!1;this.socket&&(this.socket.close(),this.socket=void 0)};
var HamsterSExtension=function(a){this.runtime=a;void 0===a.roboidCreators&&(a.roboidCreators={});a.roboidCreators.hamster=function(b){return new Hamster(b)};a.roboidCreators.hamsterS=function(b){return new HamsterS(b)};void 0===a.roboidRunner&&(a.roboidRunner=new RoboidRunner(a.roboidCreators),setTimeout(function(){a.roboidRunner.open()},1E3));a.registerPeripheralExtension("hamsterS",this);a.on("PROJECT_STOP_ALL",this.onStop.bind(this))};
HamsterSExtension.prototype.onStop=function(){this.runtime.roboidRunner&&(this.runtime.roboidRunner.reset("hamster"),this.runtime.roboidRunner.reset("hamsterS"))};
HamsterSExtension.prototype.getInfo=function(){return{id:"hamsterS",name:"\ud584\uc2a4\ud130S",color1:"#0FBD8C",color2:"#0DA57A",menuIconURI:Resource.iconURI,blockIconURI:Resource.iconURI,blocks:[{opcode:"sBoardMoveForward",text:"\ub9d0\ud310 \uc55e\uc73c\ub85c \ud55c \uce78 \uc774\ub3d9\ud558\uae30",blockType:"command",func:"sBoardMoveForward",blockCategory:"motion"},{opcode:"sBoardTurn",text:"\ub9d0\ud310 [DIRECTION]\uc73c\ub85c \ud55c \ubc88 \ub3cc\uae30",blockType:"command",arguments:{DIRECTION:{type:"string",
menu:"left_right",defaultValue:"left"}},func:"sBoardTurn",blockCategory:"motion"},"---",{opcode:"sMoveForwardUnit",text:"\uc55e\uc73c\ub85c [VALUE][UNIT] \uc774\ub3d9\ud558\uae30",blockType:"command",arguments:{VALUE:{type:"number",defaultValue:5},UNIT:{type:"string",menu:"move_unit",defaultValue:"cm"}},func:"sMoveForwardUnit",blockCategory:"motion"},{opcode:"sMoveBackwardUnit",text:"\ub4a4\ub85c [VALUE][UNIT] \uc774\ub3d9\ud558\uae30",blockType:"command",arguments:{VALUE:{type:"number",defaultValue:5},
UNIT:{type:"string",menu:"move_unit",defaultValue:"cm"}},func:"sMoveBackwardUnit",blockCategory:"motion"},{opcode:"sTurnUnitInPlace",text:"[DIRECTION]\uc73c\ub85c [VALUE][UNIT] \uc81c\uc790\ub9ac \ub3cc\uae30",blockType:"command",arguments:{DIRECTION:{type:"string",menu:"left_right",defaultValue:"left"},VALUE:{type:"number",defaultValue:90},UNIT:{type:"string",menu:"turn_unit",defaultValue:"degrees"}},func:"sTurnUnitInPlace",blockCategory:"motion"},{opcode:"sPivotAroundUnitInDirection",text:"[PART] \uc911\uc2ec\uc73c\ub85c [VALUE][UNIT] [TOWARD] \ubc29\ud5a5\uc73c\ub85c \ub3cc\uae30",
blockType:"command",arguments:{PART:{type:"string",menu:"pen_wheel",defaultValue:"left pen"},VALUE:{type:"number",defaultValue:90},UNIT:{type:"string",menu:"turn_unit",defaultValue:"degrees"},TOWARD:{type:"string",menu:"forward_backward",defaultValue:"forward"}},func:"sPivotAroundUnitInDirection",blockCategory:"motion"},{opcode:"sTurnUnitWithRadiusInDirection",text:"[PART] [DIRECTION]\uc73c\ub85c [VALUE][UNIT] \ubc18\uc9c0\ub984 [RADIUS]cm\ub97c [TOWARD] \ubc29\ud5a5\uc73c\ub85c \ub3cc\uae30",blockType:"command",
arguments:{PART:{type:"string",menu:"pen_body",defaultValue:"left pen"},DIRECTION:{type:"string",menu:"left_right",defaultValue:"left"},VALUE:{type:"number",defaultValue:90},UNIT:{type:"string",menu:"turn_unit",defaultValue:"degrees"},RADIUS:{type:"number",defaultValue:5},TOWARD:{type:"string",menu:"forward_backward",defaultValue:"forward"}},func:"sTurnUnitWithRadiusInDirection",blockCategory:"motion"},{opcode:"sChangeBothWheelsBy",text:"\uc67c\ucabd \ubc14\ud034 [LEFT] \uc624\ub978\ucabd \ubc14\ud034 [RIGHT]\ub9cc\ud07c \ubc14\uafb8\uae30",
blockType:"command",arguments:{LEFT:{type:"number",defaultValue:10},RIGHT:{type:"number",defaultValue:10}},func:"sChangeBothWheelsBy",blockCategory:"motion"},{opcode:"sSetBothWheelsTo",text:"\uc67c\ucabd \ubc14\ud034 [LEFT] \uc624\ub978\ucabd \ubc14\ud034 [RIGHT](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{LEFT:{type:"number",defaultValue:30},RIGHT:{type:"number",defaultValue:30}},func:"sSetBothWheelsTo",blockCategory:"motion"},{opcode:"sChangeWheelBy",text:"[WHEEL] \ubc14\ud034 [VALUE]\ub9cc\ud07c \ubc14\uafb8\uae30",
blockType:"command",arguments:{WHEEL:{type:"string",menu:"left_right_both",defaultValue:"left"},VALUE:{type:"number",defaultValue:10}},func:"sChangeWheelBy",blockCategory:"motion"},{opcode:"sSetWheelTo",text:"[WHEEL] \ubc14\ud034 [VALUE](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{WHEEL:{type:"string",menu:"left_right_both",defaultValue:"left"},VALUE:{type:"number",defaultValue:30}},func:"sSetWheelTo",blockCategory:"motion"},{opcode:"sFollowLineUsingFloorSensor",text:"[COLOR] \uc120\uc744 [SENSOR] \ubc14\ub2e5 \uc13c\uc11c\ub85c \ub530\ub77c\uac00\uae30",
blockType:"command",arguments:{COLOR:{type:"string",menu:"black_white",defaultValue:"black"},SENSOR:{type:"string",menu:"left_right_both",defaultValue:"left"}},func:"sFollowLineUsingFloorSensor",blockCategory:"motion"},{opcode:"sFollowLineUntilIntersection",text:"[COLOR] \uc120\uc744 \ub530\ub77c [DIRECTION] \uad50\ucc28\ub85c\uae4c\uc9c0 \uc774\ub3d9\ud558\uae30",blockType:"command",arguments:{COLOR:{type:"string",menu:"black_white",defaultValue:"black"},DIRECTION:{type:"string",menu:"left_right_front_rear",
defaultValue:"front"}},func:"sFollowLineUntilIntersection",blockCategory:"motion"},{opcode:"sSetFollowingSpeedTo",text:"\uc120 \ub530\ub77c\uac00\uae30 \uc18d\ub3c4\ub97c [SPEED](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{SPEED:{type:"string",menu:"speed",defaultValue:"5"}},func:"sSetFollowingSpeedTo",blockCategory:"motion"},{opcode:"sSetFollowingGainTo",text:"\uc120 \ub530\ub77c\uac00\uae30 \ubc29\ud5a5 \ubcc0\ud654\ub7c9\uc744 [GAIN](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",
arguments:{GAIN:{type:"string",menu:"gain",defaultValue:"default"}},func:"sSetFollowingGainTo",blockCategory:"motion"},{opcode:"sStop",text:"\uc815\uc9c0\ud558\uae30",blockType:"command",func:"sStop",blockCategory:"motion"},"---",{opcode:"sSetLedTo",text:"[LED] LED\ub97c [COLOR]\uc73c\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{LED:{type:"string",menu:"left_right_both",defaultValue:"left"},COLOR:{type:"string",menu:"led_color",defaultValue:"red"}},func:"sSetLedTo",blockCategory:"looks"},
{opcode:"sSetLedToPicker",text:"[LED] LED\ub97c [COLOR]\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{LED:{type:"string",menu:"left_right_both",defaultValue:"left"},COLOR:{type:"color",defaultValue:"#ff0000"}},func:"sSetLedToPicker",blockCategory:"looks"},{opcode:"sChangeLedByRGB",text:"[LED] LED\ub97c R: [RED] G: [GREEN] B: [BLUE]\ub9cc\ud07c \ubc14\uafb8\uae30",blockType:"command",arguments:{LED:{type:"string",menu:"left_right_both",defaultValue:"left"},RED:{type:"number",defaultValue:10},
GREEN:{type:"number",defaultValue:0},BLUE:{type:"number",defaultValue:0}},func:"sChangeLedByRGB",blockCategory:"looks"},{opcode:"sSetLedToRGB",text:"[LED] LED\ub97c R: [RED] G: [GREEN] B: [BLUE](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{LED:{type:"string",menu:"left_right_both",defaultValue:"left"},RED:{type:"number",defaultValue:255},GREEN:{type:"number",defaultValue:0},BLUE:{type:"number",defaultValue:0}},func:"sSetLedToRGB",blockCategory:"looks"},{opcode:"sClearLed",text:"[LED] LED \ub044\uae30",
blockType:"command",arguments:{LED:{type:"string",menu:"left_right_both",defaultValue:"left"}},func:"sClearLed",blockCategory:"looks"},"---",{opcode:"sPlaySoundTimes",text:"[SOUND] \uc18c\ub9ac [REPEAT]\ubc88 \uc7ac\uc0dd\ud558\uae30",blockType:"command",arguments:{SOUND:{type:"string",menu:"sound_effect",defaultValue:"beep"},REPEAT:{type:"number",defaultValue:1}},func:"sPlaySoundTimes",blockCategory:"sound"},{opcode:"sPlaySoundTimesUntilDone",text:"[SOUND] \uc18c\ub9ac [REPEAT]\ubc88 \uc7ac\uc0dd\ud558\uace0 \uae30\ub2e4\ub9ac\uae30",
blockType:"command",arguments:{SOUND:{type:"string",menu:"sound_effect",defaultValue:"beep"},REPEAT:{type:"number",defaultValue:1}},func:"sPlaySoundTimesUntilDone",blockCategory:"sound"},{opcode:"sChangeBuzzerBy",text:"\ubc84\uc800 \uc74c\uc744 [HZ]\ub9cc\ud07c \ubc14\uafb8\uae30",blockType:"command",arguments:{HZ:{type:"number",defaultValue:10}},func:"sChangeBuzzerBy",blockCategory:"sound"},{opcode:"sSetBuzzerTo",text:"\ubc84\uc800 \uc74c\uc744 [HZ](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",
arguments:{HZ:{type:"number",defaultValue:1E3}},func:"sSetBuzzerTo",blockCategory:"sound"},{opcode:"sClearSound",text:"\uc18c\ub9ac \ub044\uae30",blockType:"command",func:"sClearSound",blockCategory:"sound"},{opcode:"sPlayNote",text:"[NOTE][OCTAVE] \uc74c\uc744 \uc5f0\uc8fc\ud558\uae30",blockType:"command",arguments:{NOTE:{type:"string",menu:"note",defaultValue:"C"},OCTAVE:{type:"string",menu:"octave",defaultValue:"4"}},func:"sPlayNote",blockCategory:"sound"},{opcode:"sPlayNoteFor",text:"[NOTE][OCTAVE] \uc74c\uc744 [BEAT]\ubc15\uc790 \uc5f0\uc8fc\ud558\uae30",
blockType:"command",arguments:{NOTE:{type:"string",menu:"note",defaultValue:"C"},OCTAVE:{type:"string",menu:"octave",defaultValue:"4"},BEAT:{type:"number",defaultValue:.5}},func:"sPlayNoteFor",blockCategory:"sound"},{opcode:"sRestFor",text:"[BEAT]\ubc15\uc790 \uc26c\uae30",blockType:"command",arguments:{BEAT:{type:"number",defaultValue:.25}},func:"sRestFor",blockCategory:"sound"},{opcode:"sChangeTempoBy",text:"\uc5f0\uc8fc \uc18d\ub3c4\ub97c [BPM]\ub9cc\ud07c \ubc14\uafb8\uae30",blockType:"command",
arguments:{BPM:{type:"number",defaultValue:20}},func:"sChangeTempoBy",blockCategory:"sound"},{opcode:"sSetTempoTo",text:"\uc5f0\uc8fc \uc18d\ub3c4\ub97c [BPM]BPM\uc73c\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{BPM:{type:"number",defaultValue:60}},func:"sSetTempoTo",blockCategory:"sound"},"---",{opcode:"sLeftProximity",text:"\uc67c\ucabd \uadfc\uc811 \uc13c\uc11c",blockType:"reporter",func:"sLeftProximity",blockCategory:"sensing"},{opcode:"sRightProximity",text:"\uc624\ub978\ucabd \uadfc\uc811 \uc13c\uc11c",
blockType:"reporter",func:"sRightProximity",blockCategory:"sensing"},{opcode:"sLeftFloor",text:"\uc67c\ucabd \ubc14\ub2e5 \uc13c\uc11c",blockType:"reporter",func:"sLeftFloor",blockCategory:"sensing"},{opcode:"sRightFloor",text:"\uc624\ub978\ucabd \ubc14\ub2e5 \uc13c\uc11c",blockType:"reporter",func:"sRightFloor",blockCategory:"sensing"},{opcode:"sAccelerationX",text:"x\ucd95 \uac00\uc18d\ub3c4",blockType:"reporter",func:"sAccelerationX",blockCategory:"sensing"},{opcode:"sAccelerationY",text:"y\ucd95 \uac00\uc18d\ub3c4",
blockType:"reporter",func:"sAccelerationY",blockCategory:"sensing"},{opcode:"sAccelerationZ",text:"z\ucd95 \uac00\uc18d\ub3c4",blockType:"reporter",func:"sAccelerationZ",blockCategory:"sensing"},{opcode:"sLight",text:"\ubc1d\uae30",blockType:"reporter",func:"sLight",blockCategory:"sensing"},{opcode:"sTemperature",text:"\uc628\ub3c4",blockType:"reporter",func:"sTemperature",blockCategory:"sensing"},{opcode:"sSignalStrength",text:"\uc2e0\ud638 \uc138\uae30",blockType:"reporter",func:"sSignalStrength",
blockCategory:"sensing"},{opcode:"sWhenHandFound",text:"\uc190 \ucc3e\uc558\uc744 \ub54c",blockType:"hat",func:"sWhenHandFound",blockCategory:"sensing"},{opcode:"sWhenTilt",text:"[TILT] \ub54c",blockType:"hat",arguments:{TILT:{type:"string",menu:"when_s_tilt",defaultValue:"tilt forward"}},func:"sWhenTilt",blockCategory:"sensing"},{opcode:"sHandFound",text:"\uc190 \ucc3e\uc74c?",blockType:"Boolean",func:"sHandFound",blockCategory:"sensing"},{opcode:"sTilt",text:"[TILT]?",blockType:"Boolean",arguments:{TILT:{type:"string",
menu:"s_tilt",defaultValue:"tilt forward"}},func:"sTilt",blockCategory:"sensing"},{opcode:"sBattery",text:"\ubc30\ud130\ub9ac [BATTERY]?",blockType:"Boolean",arguments:{BATTERY:{type:"string",menu:"battery",defaultValue:"normal"}},func:"sBattery",blockCategory:"sensing"},"---",{opcode:"sSetPortTo",text:"\ud3ec\ud2b8 [PORT]\ub97c [MODE]\uc73c\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{PORT:{type:"string",menu:"port",defaultValue:"A"},MODE:{type:"string",menu:"s_mode",defaultValue:"analog input"}},
func:"sSetPortTo",blockCategory:"etc"},{opcode:"sChangeOutputBy",text:"\ucd9c\ub825 [PORT]\ub97c [VALUE]\ub9cc\ud07c \ubc14\uafb8\uae30",blockType:"command",arguments:{PORT:{type:"string",menu:"port",defaultValue:"A"},VALUE:{type:"number",defaultValue:10}},func:"sChangeOutputBy",blockCategory:"etc"},{opcode:"sSetOutputTo",text:"\ucd9c\ub825 [PORT]\ub97c [VALUE](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{PORT:{type:"string",menu:"port",defaultValue:"A"},VALUE:{type:"number",defaultValue:100}},
func:"sSetOutputTo",blockCategory:"etc"},{opcode:"sGripper",text:"\uc9d1\uac8c [ACTION]",blockType:"command",arguments:{ACTION:{type:"string",menu:"open_close",defaultValue:"open"}},func:"sGripper",blockCategory:"etc"},{opcode:"sReleaseGripper",text:"\uc9d1\uac8c \ub044\uae30",blockType:"command",func:"sReleaseGripper",blockCategory:"etc"},{opcode:"sInputA",text:"\uc785\ub825 A",blockType:"reporter",func:"sInputA",blockCategory:"etc"},{opcode:"sInputB",text:"\uc785\ub825 B",blockType:"reporter",func:"sInputB",
blockCategory:"etc"},"---",{opcode:"sWriteSerial",text:"\uc2dc\ub9ac\uc5bc [MODE] [TEXT] \uc4f0\uae30",blockType:"command",arguments:{MODE:{type:"string",menu:"serial_output",defaultValue:"string"},TEXT:{type:"string",defaultValue:"abc123"}},func:"sWriteSerial",blockCategory:"etc"},{opcode:"sReadSerialUntil",text:"\uc2dc\ub9ac\uc5bc [DELIMITER] \uc77d\uae30",blockType:"command",arguments:{DELIMITER:{type:"string",menu:"serial_delimiter",defaultValue:"all"}},func:"sReadSerialUntil",blockCategory:"etc"},
{opcode:"sSetSerialRateTo",text:"\uc2dc\ub9ac\uc5bc \uc18d\ub3c4\ub97c [BAUD]Bd\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{BAUD:{type:"string",menu:"serial_baud",defaultValue:"9600"}},func:"sSetSerialRateTo",blockCategory:"etc"},{opcode:"sSerial",text:"\uc2dc\ub9ac\uc5bc \uc785\ub825",blockType:"reporter",func:"sSerial",blockCategory:"etc"}],menus:{move_unit:[{text:"cm",value:"cm"},{text:"\ucd08",value:"seconds"},{text:"\ud384\uc2a4",value:"pulses"}],turn_unit:[{text:"\ub3c4",value:"degrees"},
{text:"\ucd08",value:"seconds"},{text:"\ud384\uc2a4",value:"pulses"}],cm_sec:[{text:"cm",value:"cm"},{text:"\ucd08",value:"seconds"}],deg_sec:[{text:"\ub3c4",value:"degrees"},{text:"\ucd08",value:"seconds"}],left_right:[{text:"\uc67c\ucabd",value:"left"},{text:"\uc624\ub978\ucabd",value:"right"}],left_right_both:[{text:"\uc67c\ucabd",value:"left"},{text:"\uc624\ub978\ucabd",value:"right"},{text:"\uc591\ucabd",value:"both"}],pen_wheel:[{text:"\uc67c\ucabd \ud39c",value:"left pen"},{text:"\uc624\ub978\ucabd \ud39c",
value:"right pen"},{text:"\uc67c\ucabd \ubc14\ud034",value:"left wheel"},{text:"\uc624\ub978\ucabd \ubc14\ud034",value:"right wheel"}],pen_body:[{text:"\uc67c\ucabd \ud39c",value:"left pen"},{text:"\uc624\ub978\ucabd \ud39c",value:"right pen"},{text:"\ub85c\ubd07",value:"robot"}],forward_backward:[{text:"\uc55e\ucabd",value:"forward"},{text:"\ub4a4\ucabd",value:"backward"}],black_white:[{text:"\uac80\uc740\uc0c9",value:"black"},{text:"\ud558\uc580\uc0c9",value:"white"}],left_right_front_rear:[{text:"\uc67c\ucabd",
value:"left"},{text:"\uc624\ub978\ucabd",value:"right"},{text:"\uc55e\ucabd",value:"front"},{text:"\ub4a4\ucabd",value:"rear"}],speed:[{text:"1",value:"1"},{text:"2",value:"2"},{text:"3",value:"3"},{text:"4",value:"4"},{text:"5",value:"5"},{text:"6",value:"6"},{text:"7",value:"7"},{text:"8",value:"8"}],gain:[{text:"\uae30\ubcf8 \uac12",value:"default"},{text:"1",value:"1"},{text:"2",value:"2"},{text:"3",value:"3"},{text:"4",value:"4"},{text:"5",value:"5"},{text:"6",value:"6"},{text:"7",value:"7"},
{text:"8",value:"8"}],led_color:[{text:"\ube68\uac04\uc0c9",value:"red"},{text:"\uc8fc\ud669\uc0c9",value:"orange"},{text:"\ub178\ub780\uc0c9",value:"yellow"},{text:"\ucd08\ub85d\uc0c9",value:"green"},{text:"\ud558\ub298\uc0c9",value:"sky blue"},{text:"\ud30c\ub780\uc0c9",value:"blue"},{text:"\ubcf4\ub77c\uc0c9",value:"violet"},{text:"\uc790\uc8fc\uc0c9",value:"purple"},{text:"\ud558\uc580\uc0c9",value:"white"}],sound_effect:[{text:"\uc090",value:"beep"},{text:"\ubb34\uc791\uc704 \uc090",value:"random beep"},
{text:"\uc9c0\uc9c0\uc9c1",value:"noise"},{text:"\uc0ac\uc774\ub80c",value:"siren"},{text:"\uc5d4\uc9c4",value:"engine"},{text:"\uca5d",value:"chop"},{text:"\ub85c\ubd07",value:"robot"},{text:"\ub514\ube44\ub514\ube44\ub525",value:"dibidibidip"},{text:"\uc798 \ud588\uc5b4\uc694",value:"good job"},{text:"\ud589\ubcf5",value:"happy"},{text:"\ud654\ub0a8",value:"angry"},{text:"\uc2ac\ud514",value:"sad"},{text:"\uc878\ub9bc",value:"sleep"},{text:"\ud589\uc9c4",value:"march"},{text:"\uc0dd\uc77c",value:"birthday"}],
note:[{text:"\ub3c4",value:"C"},{text:"\ub3c4\u266f (\ub808\u266d)",value:"C\u266f (D\u266d)"},{text:"\ub808",value:"D"},{text:"\ub808\u266f (\ubbf8\u266d)",value:"D\u266f (E\u266d)"},{text:"\ubbf8",value:"E"},{text:"\ud30c",value:"F"},{text:"\ud30c\u266f (\uc194\u266d)",value:"F\u266f (G\u266d)"},{text:"\uc194",value:"G"},{text:"\uc194\u266f (\ub77c\u266d)",value:"G\u266f (A\u266d)"},{text:"\ub77c",value:"A"},{text:"\ub77c\u266f (\uc2dc\u266d)",value:"A\u266f (B\u266d)"},{text:"\uc2dc",value:"B"}],
octave:[{text:"1",value:"1"},{text:"2",value:"2"},{text:"3",value:"3"},{text:"4",value:"4"},{text:"5",value:"5"},{text:"6",value:"6"},{text:"7",value:"7"}],when_s_tilt:[{text:"\uc55e\uc73c\ub85c \uae30\uc6b8\uc600\uc744",value:"tilt forward"},{text:"\ub4a4\ub85c \uae30\uc6b8\uc600\uc744",value:"tilt backward"},{text:"\uc67c\ucabd\uc73c\ub85c \uae30\uc6b8\uc600\uc744",value:"tilt left"},{text:"\uc624\ub978\ucabd\uc73c\ub85c \uae30\uc6b8\uc600\uc744",value:"tilt right"},{text:"\uac70\uafb8\ub85c \ub4a4\uc9d1\uc5c8\uc744",
value:"tilt flip"},{text:"\uae30\uc6b8\uc774\uc9c0 \uc54a\uc558\uc744",value:"not tilt"},{text:"\ub450\ub4dc\ub838\uc744",value:"tap"},{text:"\uc790\uc720 \ub099\ud558\ud588\uc744",value:"free fall"}],s_tilt:[{text:"\uc55e\uc73c\ub85c \uae30\uc6b8\uc784",value:"tilt forward"},{text:"\ub4a4\ub85c \uae30\uc6b8\uc784",value:"tilt backward"},{text:"\uc67c\ucabd\uc73c\ub85c \uae30\uc6b8\uc784",value:"tilt left"},{text:"\uc624\ub978\ucabd\uc73c\ub85c \uae30\uc6b8\uc784",value:"tilt right"},{text:"\uac70\uafb8\ub85c \ub4a4\uc9d1\uc74c",
value:"tilt flip"},{text:"\uae30\uc6b8\uc774\uc9c0 \uc54a\uc74c",value:"not tilt"},{text:"\ub450\ub4dc\ub9bc",value:"tap"},{text:"\uc790\uc720 \ub099\ud558",value:"free fall"}],battery:[{text:"\uc815\uc0c1",value:"normal"},{text:"\ubd80\uc871",value:"low"},{text:"\uc5c6\uc74c",value:"empty"}],port:[{text:"A",value:"A"},{text:"B",value:"B"},{text:"A\uc640 B",value:"A and B"}],s_mode:[{text:"\uc544\ub0a0\ub85c\uadf8 \uc785\ub825",value:"analog input"},{text:"\ub514\uc9c0\ud138 \uc785\ub825",value:"digital input"},
{text:"\ub514\uc9c0\ud138 \uc785\ub825 (\ud480\uc5c5)",value:"digital input (pull up)"},{text:"\ub514\uc9c0\ud138 \uc785\ub825 (\ud480\ub2e4\uc6b4)",value:"digital input (pull down)"},{text:"\uc804\uc555 \uc785\ub825",value:"voltage input"},{text:"\uc11c\ubcf4 \ucd9c\ub825",value:"servo output"},{text:"PWM \ucd9c\ub825",value:"pwm output"},{text:"\ub514\uc9c0\ud138 \ucd9c\ub825",value:"digital output"}],open_close:[{text:"\uc5f4\uae30",value:"open"},{text:"\ub2eb\uae30",value:"close"}],serial_output:[{text:"\uae00\uc790",
value:"string"},{text:"\uae00\uc790 \ud55c \uc904",value:"string line"}],serial_delimiter:[{text:"\ubaa8\ub450",value:"all"},{text:",(\uc27c\ud45c)\uae4c\uc9c0",value:"until ,(comma)"},{text:":(\uc30d\uc810)\uae4c\uc9c0",value:"until :(colon)"},{text:"$\uae4c\uc9c0",value:"until $"},{text:"#\uae4c\uc9c0",value:"until #"},{text:"\uc904 \ubc14\uafc8\uae4c\uc9c0",value:"until new line"}],serial_baud:[{text:"9600",value:"9600"},{text:"14400",value:"14400"},{text:"19200",value:"19200"},{text:"28800",value:"28800"},
{text:"38400",value:"38400"},{text:"57600",value:"57600"},{text:"76800",value:"76800"},{text:"115200",value:"115200"}]}}};HamsterSExtension.prototype.getRobot=function(a){if(void 0===a.INDEX){if(this.runtime.roboidRunner)return this.runtime.roboidRunner.getRobot("hamster",0)}else if(a=RoboidUtil.toNumber(a.INDEX,-1),0<=a&&this.runtime.roboidRunner)return this.runtime.roboidRunner.getRobot("hamster",a)};
HamsterSExtension.prototype.sBoardMoveForward=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.boardForward(c)})};HamsterSExtension.prototype.sBoardTurn=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.boardTurn(a.DIRECTION,c)})};HamsterSExtension.prototype.sMoveForward=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.moveForward(c)})};
HamsterSExtension.prototype.sMoveBackward=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.moveBackward(c)})};HamsterSExtension.prototype.sTurn=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.turn(a.DIRECTION,c)})};HamsterSExtension.prototype.sMoveForwardUnit=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.moveForwardUnit(a.VALUE,a.UNIT,c)})};
HamsterSExtension.prototype.sMoveBackwardUnit=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.moveBackwardUnit(a.VALUE,a.UNIT,c)})};HamsterSExtension.prototype.sTurnUnitInPlace=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.turnUnit(a.DIRECTION,a.VALUE,a.UNIT,c)})};
HamsterSExtension.prototype.sPivotAroundWheelUnitInDirection=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.pivotWheelUnit(a.WHEEL,a.VALUE,a.UNIT,a.TOWARD,c)})};HamsterSExtension.prototype.sTurnBodyUnitWithRadiusInDirection=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.swingBodyUnit(a.DIRECTION,a.VALUE,a.UNIT,a.RADIUS,a.TOWARD,c)})};
HamsterSExtension.prototype.sPivotAroundUnitInDirection=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.pivotUnit(a.PART,a.VALUE,a.UNIT,a.TOWARD,c)})};HamsterSExtension.prototype.sTurnUnitWithRadiusInDirection=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.swingUnit(a.PART,a.DIRECTION,a.VALUE,a.UNIT,a.RADIUS,a.TOWARD,c)})};HamsterSExtension.prototype.sChangeBothWheelsBy=function(a){var b=this.getRobot(a);b&&b.changeWheels(a.LEFT,a.RIGHT)};
HamsterSExtension.prototype.sSetBothWheelsTo=function(a){var b=this.getRobot(a);b&&b.setWheels(a.LEFT,a.RIGHT)};HamsterSExtension.prototype.sChangeWheelBy=function(a){var b=this.getRobot(a);b&&b.changeWheel(a.WHEEL,a.VALUE)};HamsterSExtension.prototype.sSetWheelTo=function(a){var b=this.getRobot(a);b&&b.setWheel(a.WHEEL,a.VALUE)};HamsterSExtension.prototype.sFollowLineUsingFloorSensor=function(a){var b=this.getRobot(a);b&&b.followLine(a.COLOR,a.SENSOR)};
HamsterSExtension.prototype.sFollowLineUntilIntersection=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.followLineUntil(a.COLOR,a.DIRECTION,c)})};HamsterSExtension.prototype.sSetFollowingSpeedTo=function(a){var b=this.getRobot(a);b&&b.setLineTracerSpeed(a.SPEED)};HamsterSExtension.prototype.sSetFollowingGainTo=function(a){var b=this.getRobot(a);b&&b.setLineTracerGain(a.GAIN)};HamsterSExtension.prototype.sStop=function(a){(a=this.getRobot(a))&&a.stop()};
HamsterSExtension.prototype.sSetLedTo=function(a){var b=this.getRobot(a);b&&b.setLed(a.LED,a.COLOR)};HamsterSExtension.prototype.sSetLedToPicker=function(a){var b=this.getRobot(a);b&&b.setRgbArray(a.LED,RoboidUtil.toRgbArray(a.COLOR))};HamsterSExtension.prototype.sChangeLedByRGB=function(a){var b=this.getRobot(a);b&&b.changeRgb(a.LED,a.RED,a.GREEN,a.BLUE)};HamsterSExtension.prototype.sSetLedToRGB=function(a){var b=this.getRobot(a);b&&b.setRgb(a.LED,a.RED,a.GREEN,a.BLUE)};
HamsterSExtension.prototype.sClearLed=function(a){var b=this.getRobot(a);b&&b.clearLed(a.LED)};HamsterSExtension.prototype.sPlaySound=function(a){var b=this.getRobot(a);b&&b.playSound(a.SOUND,1)};HamsterSExtension.prototype.sPlaySoundTimes=function(a){var b=this.getRobot(a);b&&b.playSound(a.SOUND,a.REPEAT)};HamsterSExtension.prototype.sPlaySoundTimesUntilDone=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.playSoundUntil(a.SOUND,a.REPEAT,c)})};
HamsterSExtension.prototype.sChangeBuzzerBy=function(a){var b=this.getRobot(a);b&&b.changeBuzzer(a.HZ)};HamsterSExtension.prototype.sSetBuzzerTo=function(a){var b=this.getRobot(a);b&&b.setBuzzer(a.HZ)};HamsterSExtension.prototype.sClearSound=function(a){(a=this.getRobot(a))&&a.clearSound()};HamsterSExtension.prototype.sPlayNote=function(a){var b=this.getRobot(a);b&&b.playNote(a.NOTE,a.OCTAVE)};
HamsterSExtension.prototype.sPlayNoteFor=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.playNoteBeat(a.NOTE,a.OCTAVE,a.BEAT,c)})};HamsterSExtension.prototype.sRestFor=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.restBeat(a.BEAT,c)})};HamsterSExtension.prototype.sChangeTempoBy=function(a){var b=this.getRobot(a);b&&b.changeTempo(a.BPM)};HamsterSExtension.prototype.sSetTempoTo=function(a){var b=this.getRobot(a);b&&b.setTempo(a.BPM)};
HamsterSExtension.prototype.sLeftProximity=function(a){return(a=this.getRobot(a))?a.getLeftProximity():0};HamsterSExtension.prototype.sRightProximity=function(a){return(a=this.getRobot(a))?a.getRightProximity():0};HamsterSExtension.prototype.sLeftFloor=function(a){return(a=this.getRobot(a))?a.getLeftFloor():0};HamsterSExtension.prototype.sRightFloor=function(a){return(a=this.getRobot(a))?a.getRightFloor():0};
HamsterSExtension.prototype.sAccelerationX=function(a){return(a=this.getRobot(a))?a.getAccelerationX():0};HamsterSExtension.prototype.sAccelerationY=function(a){return(a=this.getRobot(a))?a.getAccelerationY():0};HamsterSExtension.prototype.sAccelerationZ=function(a){return(a=this.getRobot(a))?a.getAccelerationZ():0};HamsterSExtension.prototype.sLight=function(a){return(a=this.getRobot(a))?a.getLight():0};
HamsterSExtension.prototype.sTemperature=function(a){return(a=this.getRobot(a))?a.getTemperature():0};HamsterSExtension.prototype.sSignalStrength=function(a){return(a=this.getRobot(a))?a.getSignalStrength():0};HamsterSExtension.prototype.sWhenHandFound=function(a){return(a=this.getRobot(a))?a.checkHandFound():!1};HamsterSExtension.prototype.sWhenTilt=function(a){var b=this.getRobot(a);return b?b.checkTilt(a.TILT):!1};
HamsterSExtension.prototype.sHandFound=function(a){return(a=this.getRobot(a))?a.checkHandFound():!1};HamsterSExtension.prototype.sTilt=function(a){var b=this.getRobot(a);return b?b.checkTilt(a.TILT):!1};HamsterSExtension.prototype.sBattery=function(a){var b=this.getRobot(a);return b?b.checkBattery(a.BATTERY):!1};HamsterSExtension.prototype.sSetPortTo=function(a){var b=this.getRobot(a);b&&b.setIoMode(a.PORT,a.MODE)};
HamsterSExtension.prototype.sChangeOutputBy=function(a){var b=this.getRobot(a);b&&b.changeOutput(a.PORT,a.VALUE)};HamsterSExtension.prototype.sSetOutputTo=function(a){var b=this.getRobot(a);b&&b.setOutput(a.PORT,a.VALUE)};HamsterSExtension.prototype.sGripper=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.gripper(a.ACTION,c)})};HamsterSExtension.prototype.sReleaseGripper=function(a){(a=this.getRobot(a))&&a.releaseGripper()};
HamsterSExtension.prototype.sInputA=function(a){return(a=this.getRobot(a))?a.getInputA():0};HamsterSExtension.prototype.sInputB=function(a){return(a=this.getRobot(a))?a.getInputB():0};HamsterSExtension.prototype.sWriteSerial=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.writeSerial(a.MODE,a.TEXT,c)})};HamsterSExtension.prototype.sReadSerialUntil=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.readSerialUltil(a.DELIMITER,c)})};
HamsterSExtension.prototype.sSetSerialRateTo=function(a){var b=this.getRobot(a);b&&b.setSerialRate(a.BAUD)};HamsterSExtension.prototype.sSerial=function(a){return(a=this.getRobot(a))?a.getSerialInput():""};Date.now||(Date.now=function(){return(new Date).getTime()});module.exports=HamsterSExtension;